# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
import numpy as np

arr = np.zeros(100, int)
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


#### 2.Создать вектор размера 100, заполненный единицами

In [247]:
arr = np.ones(100, int)
print(arr)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


#### 3.Создать вектор размера 100, заполненный числом 3

In [248]:
arr = np.full(100, 3)
print(arr)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#### 4. Как получить документацию о функции numpy.add из командной строки?

In [255]:
'''в консоль сначала прописывается "py", а затем:'''
import numpy
print(numpy.info(numpy.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 5. Поменять 2 строки в матрице

In [ ]:
arr = np.arange(4).reshape(2,2)
print(arr)
print()
arr[[0,1]] = arr[[1,0]]
print(arr)

#### 6. Создать вектор со значениями от 10 до 100

In [ ]:
arr = np.arange(10, 100)
print(arr)

#### 7. Развернуть вектор (первый становится последним)

In [ ]:
arr = np.arange(10, 100)
print(arr[::-1])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [ ]:
arr = np.arange(16).reshape(4,4)
print(arr)

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [3]:
arr = np.array([1,2,3,4,5])
step = 4
arr2 = np.zeros(len(arr) + (len(arr)-1)*(step - 1), int)
arr2[::step] = arr
print(arr2)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 10. Создать 3x3 единичную матрицу

In [190]:
arr = np.eye(3, dtype=np.int32)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 11. Создать массив 3x3x3 со случайными значениями

In [191]:
arr = np.random.randint(0, 100, (3, 3, 3))
print(arr)

[[[49 13 65]
  [31 23 91]
  [83 36 31]]

 [[18 12 77]
  [15 59 12]
  [13 52 29]]

 [[70 93 68]
  [50 27 75]
  [66 57 76]]]


#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [193]:
arr = np.random.randint(0, 100, (10, 10))
print('Массив:\n', arr)
min = arr.min()
max = arr.max()
print('\nМинимум:', min, '\nМаксимум:', max)

Массив:
 [[84 72 19 20 90 17 23 56 60 13]
 [53 73 90 29 68 85 77 65 16 60]
 [98 65 12 23 97 49 28 31 64 86]
 [77 21 50 33 43 69  1 86 57 50]
 [95 52 18 75 80 51  5 88 72 39]
 [14 96 99  1 42 95 97 34 42 57]
 [61 96 19 63 93 75 72  5 90 38]
 [36 66 37 94 11  1 50  0 85 60]
 [77 33 74 63 42 24 18 81 24 17]
 [42 55 54 89 73 18 68 34 24 25]]

Минимум: 0 
Максимум: 99


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [249]:
arr = np.random.randint(0, 10, 30)
print(arr)
mean = arr.mean()
print('\nСреднее:', mean)

[3 6 8 6 6 3 8 1 3 0 4 3 9 9 6 8 0 7 1 1 8 0 2 7 5 8 0 0 4 6]

Среднее: 4.4


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [ ]:
arr = np.ones((5, 5))
arr[1:len(arr) - 1, 1:len(arr) - 1] = 0
print(arr)

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [29]:
arr = np.ones((23, 23))
n = 1
while n < 100:
    if (n % 2 == 1 ):
        arr[n:-n, n:-n] = 0
    if (n % 2 == 0 ):
        arr[n:-n, n:-n] = 1
    n += 1
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1.

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [251]:
arr = [1, 2, 2, 4]
print(np.diag(arr, k =- 1), '\n\nИли\n')
print(np.diag(arr, k =+ 1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 4 0]] 

Или

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [263]:
arr = np.ones((8,8), dtype=int)
arr[1::2, ::2] = 0
arr[::2, 1::2] = 0
print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [264]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [267]:
print(np.tile(np.array([[1,0],[0,1]]), (4,4)))

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Перемножить матрицы 5x3 и 3x2

In [279]:
arr1 = np.random.randint(0, 100, (5, 3))
print('Матрица 5x3:\n\n', arr1)
arr2 = np.random.randint(0, 100, (3, 2))
print('\nМатрица 3x2:\n\n', arr2)
print('\nПеремноженная матрица:\n\n', np.dot(arr1, arr2))

Матрица 5x3:

 [[65 95 89]
 [20 91 13]
 [76 38 72]
 [45 68 14]
 [21 60 25]]

Матрица 3x2:

 [[38 77]
 [ 6 27]
 [75 28]]

Перемноженная матрица:

 [[ 9715 10062]
 [ 2281  4361]
 [ 8516  8894]
 [ 3168  5693]
 [ 3033  3937]]


#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [289]:
arr = np.random.randint(0, 10, 10)
print(arr)
arr[(3 < arr) & (arr < 8)] *= -1
print(arr)

[6 3 6 2 4 5 5 0 8 9]
[-6  3 -6  2 -4 -5 -5  0  8  9]


#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [292]:
arr = np.zeros((5,5), int)
arr += np.arange(5)
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 24. Есть генератор, сделать с его помощью массив

In [170]:
def generate():
    for x in xrange(5):
        yield x
        arr = np.fromiter(generate(), dtype=float, count=-1)
        
print(arr)

[[0 1]
 [2 3]]


#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [294]:
print(np.linspace(0,1,12)[1:-1])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 26. Отсортировать вектор

In [297]:
arr = np.random.randint(0, 10, 10)
print('Изначальный:\n',arr)
arr.sort()
print('\nОтсортированный:\n', arr)

Изначальный:
 [8 5 7 6 0 9 8 7 9 8]

Отсортированный:
 [0 5 6 7 7 8 8 8 9 9]


#### 27. Проверить, одинаковы ли 2 numpy массива

In [298]:
arr1 = np.random.randint(0, 10, 10)
arr2 = np.random.randint(0, 10, 10)

print(arr1)
print(arr2)

equal1 = np.allclose(arr1,arr2)
print('\n', equal1, '\n')

arr3 = np.arange(3)
arr4 = np.arange(3)

print(arr3)
print(arr4)

equal2 = np.allclose(arr3,arr3)
print('\n', equal2, '\n')

[4 2 9 1 5 3 7 2 9 3]
[3 9 3 2 6 1 2 2 4 9]

 False 

[0 1 2]
[0 1 2]

 True 



#### 28. Сделать массив неизменяемым

In [299]:
arr = np.random.randint(0, 10, 10)
arr.flags.writeable = False
arr[0] = 1

'''выдает ошибку'''

ValueError: assignment destination is read-only

#### 29. Найти n наибольших значений в массиве

In [93]:
size = int(input('Введите размерность массива'))
n = int(input('Введите размерность n (число должно быть меньше чем размер массива)'))
arr = np.random.randint(0, 100, size)
print('\nМассив:', arr)
print ('\nn наибольших чисел:', arr[np.argpartition(-arr,n)[:n]])

Введите размерность массива5
Введите размерность n (число должно быть меньше чем размер массива)2

Массив: [65 34 51 64 17]

n наибольших чисел: [65 64]


#### 30. Заменить максимальный элемент на ноль

In [304]:
arr = np.random.randint(0, 100, 10)
print('Начальный массив:\n', arr)
arr[arr.argmax()] = 0
print('\nМассив с заменой:\n', arr)

Начальный массив:
 [11 50 25 67 50 83 53 96 33 48]

Массив с заменой:
 [11 50 25 67 50 83 53  0 33 48]


#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [92]:
arr = np.zeros((10, 10), [('x', int),('y', int)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))
print(Z)

[[(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 1) (0, 1) (0, 1) (0, 1) (0, 1) (0, 1) (0, 1) (0, 1) (0, 1) (1, 1)]]


#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [94]:
x = np.arange(10)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(c))

33961.93294480225


#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [14]:
print('Целые:\n')
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
print('\nС плавающей точкой:\n')
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

Целые:

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807

С плавающей точкой:

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 34. Напечатать все значения в массиве

In [20]:
arr = np.random.randint(0, 10, 10)
for x in arr:
    print(arr[x])

5
1
5
9
4
9
4
1
8
0


#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [95]:
arr = np.arange(100)
print('Массив:\n', arr)
v = np.random.uniform(0,100)
print('Рандомное число: ', v)
index = (np.abs(arr-v)).argmin()
print('Ближайщее число: ', arr[index])

Массив:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Рандомное число:  57.56421667352124
Ближайщее число:  58


#### 36. Преобразовать массив из float в int

In [96]:
arr = np.ones(10)
print(arr)
arr = arr.astype(np.int)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]


#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [157]:
arr = np.arange(4).reshape(2, 2)

for index in np.ndindex(arr.shape):
    print(index, arr[index])
    
print('\nСам массив:\n', arr)

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3

Сам массив:
 [[0 1]
 [2 3]]


#### 38. Случайно расположить p элементов в 2D массив

In [97]:
size = int(input('Введите размерность массива'))
p = int(input('Введите кол-во элементов(p)'))

arr = np.zeros((size,size))
np.put(arr, np.random.choice(range(size*size), p, replace=False), 1)
print(arr)

Введите размерность массива5
Введите кол-во элементов(p)2
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### 39. Отнять среднее из каждой строки в матрице

In [99]:
arr = np.random.randint(0, 10, (5, 5))
print('Начальная матрица:\n', arr)
print('После вычета среднего:', arr - arr.mean(axis=1, keepdims=True))

Начальная матрица:
 [[0 6 9 6 4]
 [3 4 1 4 1]
 [8 3 0 4 8]
 [7 6 5 5 7]
 [6 5 6 4 7]]
После вычета среднего: [[-5.   1.   4.   1.  -1. ]
 [ 0.4  1.4 -1.6  1.4 -1.6]
 [ 3.4 -1.6 -4.6 -0.6  3.4]
 [ 1.   0.  -1.  -1.   1. ]
 [ 0.4 -0.6  0.4 -1.6  1.4]]


#### 40. Отсортировать матрицу по n-ому столбцу

In [130]:
arr = np.random.randint(0, 10, (4, 4))
n = int(input('Введите n (учитывая нумерацию с нуля)'))
print('Начальная:\n', arr)
print('Отсортированная:\n', arr[arr[:,n].argsort()])

Введите n (учитывая нумерацию с нуля)1
Начальная:
 [[2 6 6 1]
 [3 4 5 6]
 [0 5 0 1]
 [7 5 0 9]]
Отсортированная:
 [[3 4 5 6]
 [0 5 0 1]
 [7 5 0 9]
 [2 6 6 1]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [121]:
arr = np.random.randint(0, 2, (2, 5))
print(arr)
print('\n', (~arr.any(axis=0)).any(), '\n')
arr = np.random.randint(0, 10, (2, 10))
print(arr)
print('\n', (~arr.any(axis=0)).any(), '\n')

[[0 1 0 0 1]
 [1 0 0 0 0]]

 True 

[[2 2 3 9 0 6 8 4 1 5]
 [3 2 3 3 7 0 2 3 8 9]]

 False 



#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [138]:
arr1 = np.ones(10, int)
print('Начальный массив:\n',arr1)
arr2 = np.random.randint(0,len(arr1),20)
print('\nДругой массив:\n',arr2)
arr1 += np.bincount(arr2, minlength=len(arr1))
print('\nИзмененный начальный массив:\n',arr1)

Начальный массив:
 [1 1 1 1 1 1 1 1 1 1]

Другой массив:
 [8 9 7 4 2 3 7 1 9 6 1 3 6 9 0 9 4 9 7 8]

Измененный начальный массив:
 [2 3 2 3 3 1 3 4 3 6]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [112]:
arr = np.random.randint(0, 10, (4, 4, 4, 4))
print('Четырехмерный массив:\n', arr)
sum = arr.reshape(arr.shape[:-2] + (-1,)).sum(axis=-1)
print('Сумма:\n', sum)

Четырехмерный массив:
 [[[[9 3 6 1]
   [3 3 6 6]
   [1 6 1 7]
   [8 7 3 3]]

  [[5 5 1 1]
   [4 3 8 6]
   [0 8 7 4]
   [5 0 4 7]]

  [[4 8 8 4]
   [0 6 0 7]
   [7 4 7 2]
   [4 8 8 5]]

  [[2 9 2 8]
   [6 6 2 2]
   [4 3 4 3]
   [7 4 3 3]]]


 [[[9 5 8 2]
   [8 4 4 5]
   [0 0 8 3]
   [1 1 2 4]]

  [[6 0 0 8]
   [6 0 0 6]
   [7 0 9 2]
   [7 3 8 2]]

  [[9 7 7 1]
   [0 6 9 0]
   [7 1 5 2]
   [1 4 5 2]]

  [[9 4 0 0]
   [4 8 1 5]
   [0 4 2 2]
   [2 6 5 0]]]


 [[[0 8 4 5]
   [3 5 0 2]
   [7 2 5 8]
   [2 2 6 7]]

  [[0 5 1 5]
   [4 6 8 4]
   [7 5 9 8]
   [2 3 7 5]]

  [[4 4 6 1]
   [1 9 1 2]
   [6 5 2 7]
   [8 4 8 8]]

  [[9 3 4 8]
   [2 5 3 9]
   [0 2 0 8]
   [9 5 6 3]]]


 [[[9 6 0 9]
   [4 4 5 4]
   [4 2 9 6]
   [2 2 8 4]]

  [[1 6 4 6]
   [8 3 0 1]
   [4 8 1 2]
   [3 3 0 8]]

  [[2 3 6 2]
   [3 0 8 2]
   [8 9 6 3]
   [7 5 9 8]]

  [[5 8 0 9]
   [9 9 7 9]
   [5 5 0 2]
   [9 1 8 3]]]]
Сумма:
 [[73 68 82 68]
 [64 64 66 52]
 [66 79 76 76]
 [78 58 81 89]]
